package com.juziss.localmediahub.ble

import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.MessageDigest
import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * BLE GATT control-channel protocol. Wire format MUST match server-side
 * `server/internal/ble/protocol.go` exactly:
 *   [0]    version
 *   [1:3]  uint16 payload length (big-endian)
 *   [3:]   payload bytes
 *
 * Phase 9 (H-1b) adds the authenticated v2 frame + handshake payloads
 * below; all constants, layouts and HMAC coverage ranges mirror the Go
 * reference (Task 8, commit eb252fd) byte-for-byte. Cross-side parity is
 * locked by `BleProtocolTest.authedCodec_matchesGoReferenceVectors`, whose
 * vectors were generated by running the Go implementation.
 */
object BleProtocol {
    const val SERVICE_UUID = "fa6a3001-8b2c-4e6f-9988-123456789abc"
    const val COMMAND_CHAR_UUID = "fa6a3002-8b2c-4e6f-9988-123456789abc" // Write C -> S
    const val STATE_CHAR_UUID = "fa6a3003-8b2c-4e6f-9988-123456789abc"   // Notify S -> C

    const val FRAME_VERSION: Byte = 0x01

    /**
     * Phase 9 (H-1a/b): version byte of authenticated data frames. After the
     * mutual-challenge handshake completes, only v2 frames are accepted in
     * either direction. Mirrors Go's `FrameVersion2`.
     */
    const val FRAME_VERSION_2: Byte = 0x02

    /**
     * Frame payload decode cap. Real-device Phase 9: links negotiate ATT
     * MTU 517 (ATT data ≤ 514), and the Central sizes chunk payloads from
     * the negotiated MTU, so the old 244 ceiling rejected legitimate
     * large-chunk frames. Mirrors Go's `maxPayloadLen` (488): the largest
     * v1 frame (491 B) and v2 authed frame (491 B) both fit a 517 MTU.
     * Frames larger than the link MTU cannot arrive, so the cap is safe
     * even when a peer negotiates a smaller MTU.
     */
    const val MAX_PAYLOAD_LEN = 488

    /** seq (8B) + truncated HMAC (16B) appended to a v2 payload. */
    private const val AUTHED_OVERHEAD = 8 + 16

    /** Max payload of a v2 frame: 488 - 24 = 464 (Go `maxAuthedPayloadLen`). */
    const val MAX_AUTHED_PAYLOAD_LEN = MAX_PAYLOAD_LEN - AUTHED_OVERHEAD

    // ---- Application-layer CmdID values (payload[0]) ----
    // Mirrors server/internal/ble/protocol.go. See spec §2.2.
    const val CMD_ECHO: Byte = 0x01
    const val CMD_BOOK_INFO_REQ: Byte = 0x10

    /**
     * Task 1 (commit 48e7d4a) generalized the wire protocol so a single
     * CmdID routes to any API endpoint. The Kotlin side MUST emit a
     * byte-identical layout to Go's `EncodeApiReqPayload`:
     * `[CmdID 1B = CMD_API_REQ][Endpoint 1B][PathLen 1B][Path UTF-8][Index 2B BE]`
     *
     * Endpoints are enumerated below (`ENDPOINT_*`). See spec §2.2.
     */
    const val CMD_API_REQ: Byte = 0x11

    /**
     * PC → Android (GATT Write): one chunk of an arbitrary JSON byte stream.
     * Task 1 renamed this from `CMD_BOOK_CHAPTER_CHUNK`; the chunk layout is
     * unchanged — only the semantics broadened (any JSON, not just chapter
     * Block arrays).
     */
    const val CMD_JSON_CHUNK: Byte = 0x12

    /**
     * Phase 9 (H-1a/b) mutual-challenge handshake command, PC → Android.
     * Payload: `[CmdID 1B][Dir 1B][Nonce 8B]` (10 B), carried in a v1 frame.
     * Mirrors Go's `CmdAuthChallenge`.
     */
    const val CMD_AUTH_CHALLENGE: Byte = 0x20

    /**
     * Phase 9 (H-1a/b) handshake answer. Payload:
     * `[CmdID 1B][Nonce 8B][MAC 16B]` (25 B) where
     * MAC = HMAC-SHA256(key, nonce||dir)[:16]. Carried in a v1 frame.
     * Mirrors Go's `CmdAuthResponse`.
     */
    const val CMD_AUTH_RESPONSE: Byte = 0x21

    /**
     * Direction byte of a handshake challenge: which role issued it. Bound
     * into the response MAC so a challenge captured in one direction cannot
     * be replayed as the other direction's proof. Mirrors Go's
     * `AuthDirCentralToPeripheral` (0x01, PC 验证手机).
     */
    const val AUTH_DIR_C2P: Byte = 0x01

    /** Phone → PC challenge direction. Mirrors Go's `AuthDirPeripheralToCentral` (0x02, 手机验证 PC). */
    const val AUTH_DIR_P2C: Byte = 0x02

    // ---- Endpoint enumeration (payload[1] of a CMD_API_REQ frame) ----
    // Mirrors Go's `Endpoint` enum in server/internal/ble/protocol.go (Task 1).
    /** Chapter blocks (legacy BookChapter API). */
    const val ENDPOINT_BOOK_CHAPTER: Byte = 0x01
    /** Folder list API. */
    const val ENDPOINT_FOLDERS: Byte = 0x02
    /** Browse-folder API (paginated entries). */
    const val ENDPOINT_BROWSE_FOLDER: Byte = 0x03
    /** Book metadata API. */
    const val ENDPOINT_BOOK_INFO: Byte = 0x04

    /**
     * Segmented chapter-blocks API (degraded-reading throughput fix): a
     * single-chapter txt novel can be megabytes, so the reader pulls the
     * chapter in ~180KB segments. `index` selects the chapter; `index2`
     * (the request's trailing uint16) is the BLOCK OFFSET of the segment.
     * Response shape: {"offset":N,"total":T,"blocks":[...]}.
     */
    const val ENDPOINT_BOOK_CHAPTER_SEGMENT: Byte = 0x05

    /** Per-chunk payload cap (spec §1.2). Pure advisory; not enforced here. */
    const val MAX_CHUNK_PAYLOAD_BYTES = 200

    data class Frame(val payload: ByteArray) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is Frame) return false
            return payload.contentEquals(other.payload)
        }
        override fun hashCode(): Int = payload.contentHashCode()
    }

    /**
     * Decoded authenticated v2 frame: the (verified) payload and the 64-bit
     * per-direction sequence number. Replay/rollback enforcement is stateful
     * and lives in [BleController], mirroring Go's Central receive gate.
     */
    data class AuthedFrame(val payload: ByteArray, val seq: ULong) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is AuthedFrame) return false
            return payload.contentEquals(other.payload) && seq == other.seq
        }
        override fun hashCode(): Int = payload.contentHashCode() * 31 + seq.hashCode()
    }

    fun encodeFrame(payload: ByteArray): ByteArray {
        val buf = ByteBuffer.allocate(3 + payload.size).order(ByteOrder.BIG_ENDIAN)
        buf.put(FRAME_VERSION)
        // length as uint16 big-endian
        buf.put(((payload.size shr 8) and 0xFF).toByte())
        buf.put((payload.size and 0xFF).toByte())
        buf.put(payload)
        return buf.array()
    }

    fun decodeFrame(data: ByteArray): Frame? {
        if (data.size < 3) return null
        if (data[0] != FRAME_VERSION) return null
        val length = ((data[1].toInt() and 0xFF) shl 8) or (data[2].toInt() and 0xFF)
        if (length > MAX_PAYLOAD_LEN) return null
        if (data.size < 3 + length) return null
        return Frame(data.copyOfRange(3, 3 + length))
    }

    // ------------------------------------------------------------------
    // Phase 9 (Task 9, H-1b): authenticated v2 frames. Go reference:
    // server/internal/ble/protocol.go `EncodeAuthedFrame` / `DecodeAuthedFrame`
    // (Task 8, commit eb252fd).
    // ------------------------------------------------------------------

    /**
     * Derives the 32-byte BLE channel key from the server's Bearer token:
     * `sha256("lmh-ble-v1:" + token)`. The domain-separation prefix keeps
     * this hash distinct from any other use of the token. MUST NOT be called
     * with an empty token — `sha256("lmh-ble-v1:")` is publicly computable
     * (the prefix is a constant); [BleController] refuses the auth flow when
     * no token is configured (Go symmetric: `SetAuthToken("")` stores nil).
     */
    fun deriveBleAuthKey(token: String): ByteArray =
        MessageDigest.getInstance("SHA-256")
            .digest("lmh-ble-v1:$token".toByteArray(Charsets.UTF_8))

    /**
     * Wraps payload in a v2 authenticated frame:
     *
     * `[0x02][len 2B BE][payload ≤220B][seq 8B BE][hmac 16B]`
     *
     * HMAC-SHA256(key) covers `[0 : 3+len+8]` (version, length, payload,
     * seq) and is truncated to 16 bytes. Callers pass a strictly-increasing
     * per-direction seq; the receiver rejects rollback/replay. Payloads over
     * [MAX_AUTHED_PAYLOAD_LEN] are defensively truncated (Go parity — the
     * caller's chunker already bounds chunks to 200 B).
     */
    fun encodeAuthedFrame(payload: ByteArray, seq: ULong, key: ByteArray): ByteArray {
        val p = if (payload.size > MAX_AUTHED_PAYLOAD_LEN) payload.copyOf(MAX_AUTHED_PAYLOAD_LEN) else payload
        val buf = ByteArray(3 + p.size + AUTHED_OVERHEAD)
        buf[0] = FRAME_VERSION_2
        buf[1] = ((p.size shr 8) and 0xFF).toByte()
        buf[2] = (p.size and 0xFF).toByte()
        System.arraycopy(p, 0, buf, 3, p.size)
        writeUint64BE(buf, 3 + p.size, seq)
        val mac = hmacSha256Trunc16(key, buf, 0, 3 + p.size + 8)
        System.arraycopy(mac, 0, buf, 3 + p.size + 8, 16)
        return buf
    }

    /**
     * Verifies and parses a v2 authenticated frame. Returns the payload and
     * seq, or null when the structure is malformed or the truncated HMAC
     * fails to verify (tampered frame / wrong key). The seq is NOT checked
     * here — replay/rollback rejection is stateful (max-seen per direction)
     * and lives in [BleController], mirroring Go's Central.
     *
     * Note (Go parity): the version byte is not explicitly checked — the
     * HMAC covers it and the length checks bound the structure, so any
     * differently-versioned frame fails MAC or structure either way.
     */
    fun decodeAuthedFrame(data: ByteArray, key: ByteArray): AuthedFrame? {
        if (data.size < 3 + AUTHED_OVERHEAD) return null
        val length = ((data[1].toInt() and 0xFF) shl 8) or (data[2].toInt() and 0xFF)
        if (length > MAX_AUTHED_PAYLOAD_LEN) return null
        if (data.size < 3 + length + AUTHED_OVERHEAD) return null
        val want = hmacSha256Trunc16(key, data, 0, 3 + length + 8)
        // Constant-time comparison (Go uses subtle.ConstantTimeCompare).
        if (!MessageDigest.isEqual(want, data.copyOfRange(3 + length + 8, 3 + length + 24))) return null
        val seq = readUint64BE(data, 3 + length)
        return AuthedFrame(data.copyOfRange(3, 3 + length), seq)
    }

    // ------------------------------------------------------------------
    // Phase 9 (Task 9, H-1b): handshake payload codecs. Carried in v1
    // frames (`encodeFrame`); Go reference: `EncodeAuthChallengePayload` /
    // `DecodeAuthChallengePayload` / `AuthResponseMAC` /
    // `EncodeAuthResponsePayload` / `DecodeAuthResponsePayload`.
    // ------------------------------------------------------------------

    /** Builds `[CmdID 1B][dir 1B][nonce ≤8B]` (always 10 B, nonce zero-padded). */
    fun encodeAuthChallengePayload(dir: Byte, nonce: ByteArray): ByteArray {
        val out = ByteArray(10)
        out[0] = CMD_AUTH_CHALLENGE
        out[1] = dir
        System.arraycopy(nonce, 0, out, 2, minOf(8, nonce.size))
        return out
    }

    /** Parses a challenge payload → (dir, nonce 8B); null when malformed. */
    fun decodeAuthChallengePayload(p: ByteArray): Pair<Byte, ByteArray>? {
        if (p.size < 10 || p[0] != CMD_AUTH_CHALLENGE) return null
        return p[1] to p.copyOfRange(2, 10)
    }

    /**
     * Computes the proof for a challenge: 16-byte truncated HMAC-SHA256 over
     * `nonce || dir`. Binding the direction byte prevents a challenge issued
     * in one direction being answered as the other's.
     */
    fun authResponseMac(key: ByteArray, nonce: ByteArray, dir: Byte): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        mac.update(nonce)
        mac.update(byteArrayOf(dir))
        return mac.doFinal().copyOf(16)
    }

    /** Builds `[CmdID 1B][nonce ≤8B][mac16 ≤16B]` (always 25 B, zero-padded). */
    fun encodeAuthResponsePayload(nonce: ByteArray, mac16: ByteArray): ByteArray {
        val out = ByteArray(25)
        out[0] = CMD_AUTH_RESPONSE
        System.arraycopy(nonce, 0, out, 1, minOf(8, nonce.size))
        System.arraycopy(mac16, 0, out, 9, minOf(16, mac16.size))
        return out
    }

    /** Parses a response payload → (nonce 8B, mac 16B); null when malformed. */
    fun decodeAuthResponsePayload(p: ByteArray): Pair<ByteArray, ByteArray>? {
        if (p.size < 25 || p[0] != CMD_AUTH_RESPONSE) return null
        return p.copyOfRange(1, 9) to p.copyOfRange(9, 25)
    }

    // ------------------------------------------------------------------
    // CMD_JSON_CHUNK payload encoder (Go `EncodeJsonChunkPayload` parity):
    // `[CmdID 1B][TotalChunks 2B BE][ChunkIndex 2B BE][TotalBytes 2B BE]
    //  [ChunkLen 2B BE][Chunk Bytes]`. Fields truncate to uint16 exactly as
    // the Go encoder does.
    // ------------------------------------------------------------------

    fun encodeJsonChunkPayload(
        totalChunks: Int,
        chunkIndex: Int,
        totalBytes: Int,
        chunk: ByteArray,
    ): ByteArray {
        val out = ByteArray(9 + chunk.size)
        out[0] = CMD_JSON_CHUNK
        putUint16BE(out, 1, totalChunks)
        putUint16BE(out, 3, chunkIndex)
        putUint16BE(out, 5, totalBytes)
        putUint16BE(out, 7, chunk.size)
        System.arraycopy(chunk, 0, out, 9, chunk.size)
        return out
    }

    // ---- shared BE integer helpers ----

    private fun putUint16BE(buf: ByteArray, off: Int, v: Int) {
        buf[off] = ((v shr 8) and 0xFF).toByte()
        buf[off + 1] = (v and 0xFF).toByte()
    }

    private fun writeUint64BE(buf: ByteArray, off: Int, v: ULong) {
        for (i in 0 until 8) {
            buf[off + i] = ((v shr ((7 - i) * 8)) and 0xFFuL).toByte()
        }
    }

    private fun readUint64BE(buf: ByteArray, off: Int): ULong {
        var v = 0uL
        for (i in 0 until 8) {
            v = (v shl 8) or ((buf[off + i].toLong() and 0xFF).toULong())
        }
        return v
    }

    private fun hmacSha256Trunc16(key: ByteArray, data: ByteArray, off: Int, len: Int): ByteArray {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        mac.update(data, off, len)
        return mac.doFinal().copyOf(16)
    }
}
