// 从 open-props 抽取白名单 token 子集到 tokens.css。
// 只抽取我们需要的 size/radius/shadow；颜色由 style.css 自己定义（与 readerPrefs 对齐）。
// 运行：npm run build:tokens
//
// 注意：open-props 1.7.7 的 *.min.css 是单行压缩格式，没有换行符，
// 因此用声明级正则（匹配 `--token:value;` 片段）抽取，而不是按行匹配。
// 另外，1.7.7 没有独立 radius.min.css，--radius-* 实际定义在 borders.min.css 中。
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const WEB_DIR = dirname(HERE);
const OP = join(WEB_DIR, 'node_modules', 'open-props');

// 白名单：每条 = (源文件名, 抽取声明的正则)
const SOURCES = [
    // sizes（间距）
    ['sizes.min.css', /--size-(extra-)?(small|large|[0-9]+):[^;]+;/g],
    // radius（1.7.7 把 --radius-* 放在 borders.min.css）
    ['borders.min.css', /--radius-[a-z0-9-]+:[^;]+;/g],
    // shadows
    ['shadows.min.css', /--shadow-[a-z0-9-]+:[^;]+;/g],
];

function pickRules(text, pattern) {
    return [...text.matchAll(pattern)].map(m => '  ' + m[0].trim());
}

const lines = ['/* AUTO-GENERATED by tools/build-tokens.mjs — do not edit by hand. */', ':root {'];
for (const [fname, pat] of SOURCES) {
    const p = join(OP, fname);
    const txt = await readFile(p, 'utf8').catch(() => '');
    if (!txt) {
        console.warn(`[build-tokens] WARN: ${fname} not found in open-props — skipping`);
        continue;
    }
    lines.push(...pickRules(txt, pat));
}
lines.push('}');

const out = lines.join('\n') + '\n';
await writeFile(join(WEB_DIR, 'tokens.css'), out);
console.log(`[build-tokens] wrote tokens.css (${out.split('\n').length} lines)`);
