package com.juziss.localmediahub.ble

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test

class BleProtocolTest {

    @Test
    fun roundTrip_preservesPayload() {
        val payload = "hello-ble".toByteArray()
        val encoded = BleProtocol.encodeFrame(payload)
        val frame = BleProtocol.decodeFrame(encoded)
        assertArrayEquals(payload, frame?.payload)
    }

    @Test
    fun decode_returnsNullForTruncatedInput() {
        // Header only, no payload.
        val headerOnly = byteArrayOf(BleProtocol.FRAME_VERSION, 0x05, 0x00)
        assertNull(BleProtocol.decodeFrame(headerOnly))
    }

    @Test
    fun uuids_areDistinctAndMatchServerContract() {
        assertEquals("fa6a3001-8b2c-4e6f-9988-123456789abc", BleProtocol.SERVICE_UUID)
        assertEquals("fa6a3002-8b2c-4e6f-9988-123456789abc", BleProtocol.COMMAND_CHAR_UUID)
        assertEquals("fa6a3003-8b2c-4e6f-9988-123456789abc", BleProtocol.STATE_CHAR_UUID)
    }

    // ------------------------------------------------------------------
    // Phase 9 (Task 9, H-1b): authenticated v2 frames + handshake payloads.
    // Wire format mirrors server/internal/ble/protocol.go byte-for-byte;
    // the cross-side known-answer vectors below were generated by running
    // the Go implementation (commit eb252fd) on the same inputs.
    // ------------------------------------------------------------------

    @Test
    fun authedFrameRoundTripAndTamper() {
        val key = BleProtocol.deriveBleAuthKey("sekrit")
        val frame = BleProtocol.encodeAuthedFrame(byteArrayOf(0x01, 1, 2), 7uL, key)
        val decoded = BleProtocol.decodeAuthedFrame(frame, key)
        assertEquals(7uL, decoded?.seq)
        assertEquals(0x01.toByte(), decoded?.payload?.first())
        frame[frame.size - 1] = (frame.last().toInt() xor 0xFF).toByte()
        // NOTE: JUnit 4's assertNull is (message, object) — the task brief's
        // snippet had these inverted; order fixed here, semantics unchanged.
        assertNull("tampered frame must fail", BleProtocol.decodeAuthedFrame(frame, key))
        assertNull(
            "wrong key must fail",
            BleProtocol.decodeAuthedFrame(frame, BleProtocol.deriveBleAuthKey("other")),
        )
    }

    @Test
    fun authChallengeResponseRoundTrip() {
        val key = BleProtocol.deriveBleAuthKey("sekrit")
        val nonce = ByteArray(8) { it.toByte() }
        val ch = BleProtocol.encodeAuthChallengePayload(BleProtocol.AUTH_DIR_C2P, nonce)
        val dec = BleProtocol.decodeAuthChallengePayload(ch)!!
        assertEquals(BleProtocol.AUTH_DIR_C2P, dec.first)
        val mac = BleProtocol.authResponseMac(key, nonce, BleProtocol.AUTH_DIR_C2P)
        val resp = BleProtocol.encodeAuthResponsePayload(nonce, mac)
        val (rn, rm) = BleProtocol.decodeAuthResponsePayload(resp)!!
        assertArrayEquals(nonce, rn)
        assertArrayEquals(mac, rm)
    }

    /**
     * Cross-side known-answer vectors: each hex string was produced by the Go
     * reference implementation (`server/internal/ble/protocol.go`, Task 8,
     * commit eb252fd) for the same key/inputs. ANY byte drift in the Kotlin
     * codec (field order, endianness, HMAC coverage, truncation) fails here —
     * this is the hard parity lock for the Phase 9 wire format.
     */
    @Test
    fun authedCodec_matchesGoReferenceVectors() {
        val key = BleProtocol.deriveBleAuthKey("sekrit")
        assertArrayEquals(
            hex("a1deb6273c1470657719e78afcd620ad214283fa568fa1358395ac29dc280941"),
            key,
        )
        assertArrayEquals(
            hex("0200030101020000000000000007eb422987077e1c0e62e3247acee7b033"),
            BleProtocol.encodeAuthedFrame(byteArrayOf(0x01, 1, 2), 7uL, key),
        )
        val nonce = byteArrayOf(0, 1, 2, 3, 4, 5, 6, 7)
        assertArrayEquals(
            hex("20010001020304050607"),
            BleProtocol.encodeAuthChallengePayload(BleProtocol.AUTH_DIR_C2P, nonce),
        )
        assertArrayEquals(
            hex("cddeed9e25ea8e8d41d23e6357aea2bd"),
            BleProtocol.authResponseMac(key, nonce, BleProtocol.AUTH_DIR_C2P),
        )
        val mac = BleProtocol.authResponseMac(key, nonce, BleProtocol.AUTH_DIR_C2P)
        assertArrayEquals(
            hex("210001020304050607cddeed9e25ea8e8d41d23e6357aea2bd"),
            BleProtocol.encodeAuthResponsePayload(nonce, mac),
        )
        // Max uint64 seq edge — verifies all 8 seq bytes are written BE.
        assertArrayEquals(
            hex("02000212aaffffffffffffffff438838b9ec4a236b17fbf4ecba946399"),
            BleProtocol.encodeAuthedFrame(byteArrayOf(0x12, 0xAA.toByte()), ULong.MAX_VALUE, key),
        )
        // 221-byte payload is defensively truncated to 220 (Go parity). The
        // Go reference frame for this input is 247 bytes total with length
        // field 0x00DC and MAC tail b60f5ac22576b3777b78ff5e1f4cb79e — the
        // truncated HMAC covers every preceding byte, so matching the Go MAC
        // here locks the entire 220-byte layout without pasting the vector.
        val big = ByteArray(221) { (it % 251).toByte() }
        val trunc = BleProtocol.encodeAuthedFrame(big, 0uL, key)
        assertEquals(247, trunc.size)
        assertEquals(0x02.toByte(), trunc[0])
        assertEquals(0xDC, (trunc[1].toInt() and 0xFF) shl 8 or (trunc[2].toInt() and 0xFF))
        assertArrayEquals(
            hex("b60f5ac22576b3777b78ff5e1f4cb79e"),
            trunc.copyOfRange(trunc.size - 16, trunc.size),
        )
        // And the truncated frame still round-trips with seq 0.
        val decoded = BleProtocol.decodeAuthedFrame(trunc, key)
        assertNotNull(decoded)
        assertEquals(0uL, decoded?.seq)
        assertEquals(220, decoded?.payload?.size)
        assertEquals(0xDB.toByte(), decoded?.payload?.last())
    }

    /** seq must be strictly per-direction but the codec accepts any value; decode returns it verbatim. */
    @Test
    fun decodeAuthedFrame_rejectsTruncatedAndOversized() {
        val key = BleProtocol.deriveBleAuthKey("sekrit")
        val frame = BleProtocol.encodeAuthedFrame(byteArrayOf(0x01), 0uL, key)
        // Strip the last MAC byte → structural truncation.
        assertNull(BleProtocol.decodeAuthedFrame(frame.copyOf(frame.size - 1), key))
        // Length field claims more payload than present.
        val forged = frame.copyOf()
        forged[1] = 0x01
        assertNull(BleProtocol.decodeAuthedFrame(forged, key))
    }

    private fun hex(s: String): ByteArray = s.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
